/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.MyList;
import Modelo.Analista;
import Modelo.Empleado;
import Modelo.Excepciones;
import Modelo.Fecha;
import Modelo.Programador;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class InterefazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterefazGrafica
     */
    
    
    MyList lista = new MyList();
    
    public InterefazGrafica() {
        initComponents();
        
        botonAnterior.setEnabled(false);
         try
        {
            lista.add(new Analista(50, "David", 1200, 1300, new Fecha(03,11, 2015), 2, "dmenndezz"), 50);
        }catch(Excepciones e){
            System.out.println(e.getMessage());
        }
        
        try
        {
            lista.add(new Analista(4, "Pablo", 1050, 1300, new Fecha(15, 11, 2016), 1, "bypablopablete"), 4);
        }catch(Excepciones e){
            System.out.println(e.getMessage());
        }
        
        try
        {
            lista.add(new Programador(2, "Juan", 1200, 1450, new Fecha(07,04, 2023), 3, 5 ), 2);
        }catch(Excepciones e){
            System.out.println(e.getMessage());
        }
        
        try
        {
            lista.add(new Programador(7, "Pedro", 1400, 1500, new Fecha(27, 12, 2019), 2, 2), 7);
        }catch(Excepciones e){
            System.out.println(e.getMessage());
        }
        
        try
        {
            lista.add(new Analista(3, "Manuel", 1300, 1350, new Fecha(20, 03, 1999), 2, "pablete"), 3);
        }catch(Excepciones e){
            System.out.println(e.getMessage());
        }
        
        mostrarEmpleados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSueldoMax = new javax.swing.JTextField();
        botonCargarEmpleados = new javax.swing.JButton();
        botonGuardarFichero = new javax.swing.JButton();
        botonCrearEmpleado = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTipoEmpleado = new javax.swing.JTextField();
        botonCreadoMasivo = new javax.swing.JButton();
        botonAnterior = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        botonOrdenar = new javax.swing.JButton();
        botonCalcular = new javax.swing.JButton();
        labelDato1 = new javax.swing.JLabel();
        labelDato2 = new javax.swing.JLabel();
        txtDatoA = new javax.swing.JTextField();
        txtDatoB = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonPrimero = new javax.swing.JButton();
        botonUltimo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 0, 0));
        jLabel1.setText("EMPLEADOS");

        jLabel2.setText("Número:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Sueldo:");

        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha:");

        jLabel6.setText("/");

        txtMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesActionPerformed(evt);
            }
        });

        jLabel7.setText("/");

        jLabel8.setText("Sueldo Máximo:");

        botonCargarEmpleados.setText("Cargar fichero");
        botonCargarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarEmpleadosActionPerformed(evt);
            }
        });

        botonGuardarFichero.setText("Guardar fichero");
        botonGuardarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarFicheroActionPerformed(evt);
            }
        });

        botonCrearEmpleado.setText("Crear empleado");
        botonCrearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearEmpleadoActionPerformed(evt);
            }
        });

        jLabel9.setText("Tipo de empleado:");

        botonCreadoMasivo.setText("Creado masivo");

        botonAnterior.setText("<--- Anterior");
        botonAnterior.setMaximumSize(new java.awt.Dimension(113, 25));
        botonAnterior.setMinimumSize(new java.awt.Dimension(113, 25));
        botonAnterior.setPreferredSize(new java.awt.Dimension(113, 25));
        botonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnteriorActionPerformed(evt);
            }
        });

        botonSiguiente.setText("Siguiente --->");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        botonOrdenar.setLabel("Ordenar");
        botonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenarActionPerformed(evt);
            }
        });

        botonCalcular.setLabel("Calcular");

        labelDato1.setText("Plus Anual:");

        labelDato2.setText("Nombre de Usuario:");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonPrimero.setText("Ir al primero");
        botonPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrimeroActionPerformed(evt);
            }
        });

        botonUltimo.setText("Ir al último");
        botonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonGuardarFichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(botonCargarEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSueldo)
                            .addComponent(txtSueldoMax, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6)
                                .addGap(9, 9, 9)
                                .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botonCrearEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonCreadoMasivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTipoEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(txtNum, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDato1)
                                    .addComponent(labelDato2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDatoA)
                                    .addComponent(txtDatoB, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(botonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(botonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botonSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 32, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDato1)
                    .addComponent(txtDatoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDato2)
                    .addComponent(txtDatoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSueldoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCargarEmpleados)
                            .addComponent(botonCrearEmpleado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonGuardarFichero)
                            .addComponent(botonCreadoMasivo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonOrdenar)
                            .addComponent(botonCalcular)))
                    .addComponent(botonAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrar)
                    .addComponent(botonPrimero)
                    .addComponent(botonUltimo))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumActionPerformed

    private void txtMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesActionPerformed

    private void botonCargarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarEmpleadosActionPerformed
        cargarDatosFichero();
    }//GEN-LAST:event_botonCargarEmpleadosActionPerformed

    private void botonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnteriorActionPerformed
        retroceder();
    }//GEN-LAST:event_botonAnteriorActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        avanzar();
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void botonGuardarFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarFicheroActionPerformed
        try {
            guardarDatosFichero();
        } catch (IOException ex) {
            Logger.getLogger(InterefazGrafica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InterefazGrafica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonGuardarFicheroActionPerformed

    private void botonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenarActionPerformed
        try {
            ordenar();
        } catch(Exception ex){}
        
    }//GEN-LAST:event_botonOrdenarActionPerformed

    private void botonCrearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearEmpleadoActionPerformed
            modoCrear();
    }//GEN-LAST:event_botonCrearEmpleadoActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        try {
            crearEmpleado();
            mostrarEmpleados();
            salirModoCrear();
        } catch (Excepciones ex) {
            Logger.getLogger(InterefazGrafica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        salirModoCrear();
        mostrarEmpleados();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        borrarEmpleado();
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUltimoActionPerformed
        if(lista.isLast())
        {
            JOptionPane.showMessageDialog(this, "Ya estás en el último nodo");
        }
        else
        {
            irUltimo();
        }
    }//GEN-LAST:event_botonUltimoActionPerformed

    private void botonPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrimeroActionPerformed
        if(lista.isFirst())
        {
            JOptionPane.showMessageDialog(this, "Ya estás en el primer nodo");
        }
        else
        {
            irPrimero();
        }
    }//GEN-LAST:event_botonPrimeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterefazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterefazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterefazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterefazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterefazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAnterior;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCargarEmpleados;
    private javax.swing.JButton botonCreadoMasivo;
    private javax.swing.JButton botonCrearEmpleado;
    private javax.swing.JButton botonGuardarFichero;
    private javax.swing.JButton botonOrdenar;
    private javax.swing.JButton botonPrimero;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JButton botonUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelDato1;
    private javax.swing.JLabel labelDato2;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDatoA;
    private javax.swing.JTextField txtDatoB;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtSueldoMax;
    private javax.swing.JTextField txtTipoEmpleado;
    // End of variables declaration//GEN-END:variables

    private void irPrimero()
    {
        while(lista.isFirst() == false)
        {
            lista.avanzar();
        }
        botonSiguiente.setEnabled(false);
        botonAnterior.setEnabled(true);
        mostrarEmpleados();
    }
    
    private void irUltimo()
    {
        while(lista.isLast() == false)
        {
            lista.retroceder();
        }
        botonSiguiente.setEnabled(true);
        botonAnterior.setEnabled(false);
        mostrarEmpleados();
    }
    
    private void modoCrear()
    {
        vaciarCasillas();
        botonAceptar.setEnabled(true);
        botonCancelar.setEnabled(true);
        botonCargarEmpleados.setEnabled(false);
        botonGuardarFichero.setEnabled(false);
        botonSiguiente.setEnabled(false);
        botonAnterior.setEnabled(false);
        botonOrdenar.setEnabled(false);
        botonCreadoMasivo.setEnabled(false);
        botonCrearEmpleado.setEnabled(false);
        botonCalcular.setEnabled(false);
        cambiarLabels();
    }
    
    private void salirModoCrear()
    {
        botonCargarEmpleados.setEnabled(true);
        botonGuardarFichero.setEnabled(true);
        botonSiguiente.setEnabled(true);
        botonAnterior.setEnabled(false);
        botonOrdenar.setEnabled(true);
        botonCreadoMasivo.setEnabled(true);
        botonCrearEmpleado.setEnabled(true);
        botonCalcular.setEnabled(true);
        botonAceptar.setEnabled(false);
        botonCancelar.setEnabled(false);
    }
    
    private void cambiarLabels()
    {
        labelDato1.setText("Dato 1:");
        labelDato2.setText("Dato 2:");
    }
    
    private void crearEmpleado() throws Excepciones
    {
        cambiarLabels();
        
        if(txtTipoEmpleado.getText().equals("Analista"))
        {
            try
            {
                lista.add(new Analista(Integer.parseInt(txtNum.getText()), txtNombre.getText(), Integer.parseInt(txtSueldo.getText()), Integer.parseInt(txtSueldoMax.getText()), new Fecha(Integer.parseInt(txtDia.getText()), Integer.parseInt(txtMes.getText()), Integer.parseInt(txtAnio.getText())), Integer.parseInt(txtDatoA.getText()), txtDatoB.getText()), Integer.parseInt(txtNum.getText()));
            }catch(Excepciones e){
                System.out.println(e.getMessage());
            }  
        }
        else
        {
            try
            {
                lista.add(new Programador(Integer.parseInt(txtNum.getText()), txtNombre.getText(), Integer.parseInt(txtSueldo.getText()), Integer.parseInt(txtSueldoMax.getText()), new Fecha(Integer.parseInt(txtDia.getText()), Integer.parseInt(txtMes.getText()), Integer.parseInt(txtAnio.getText())), Integer.parseInt(txtDatoA.getText()), Integer.parseInt(txtDatoB.getText())), Integer.parseInt(txtNum.getText()));
            }catch(Excepciones e){
                System.out.println(e.getMessage());
            }
        }
        
    }
    
    private void vaciarCasillas()
    {
        txtAnio.setText("");
        txtMes.setText("");
        txtDia.setText("");
        txtNombre.setText("");
        txtNum.setText("");
        txtSueldo.setText("");
        txtSueldoMax.setText("");
        txtTipoEmpleado.setText("");
        txtDatoA.setText("");
        txtDatoB.setText("");
        
    }
    
    private void mostrarEmpleados()
    {
        Empleado e1 = (Empleado) lista.getActualNode().getMain();
        
        if(e1.getClass().getSimpleName().contains("Analista"))
        {
            txtTipoEmpleado.setText("Analista");
            Analista analista = (Analista)e1;
            txtDatoA.setText("" + analista.getPlusAnual());
            txtDatoB.setText("" + analista.getNombreUsuario());
        }
        else
        {
            txtTipoEmpleado.setText("Programador");
            Programador prog = (Programador)e1;
            txtDatoA.setText("" + prog.getSueldoExtra());
            txtDatoB.setText("" + prog.getNumeroProgramas());
        }
        txtNum.setText("" + e1.getNumero());
        txtNombre.setText(e1.getNombre());
        txtSueldo.setText("" + e1.getSueldo());
        txtSueldoMax.setText("" + e1.getSueldoMaximo());
        txtDia.setText("" + e1.getFechaAlta().getDia());
        txtMes.setText("" + e1.getFechaAlta().getMes());
        txtAnio.setText("" + e1.getFechaAlta().getAnio());
        
        diferenciarTipo();
    }
    
    public void borrarEmpleado()
    {
        if(lista.isFirst())
        {
            lista.removeElement();
            lista.retroceder();
            mostrarEmpleados();
        }
        else if(lista.isLast())
        {
            lista.removeElement();
            lista.avanzar();
            mostrarEmpleados();
        }
        else
        {
            lista.removeElement();
            lista.avanzar();
            mostrarEmpleados();
        }
            if(lista.isFirst() && lista.isLast())
            {
                botonSiguiente.setEnabled(false);
                botonAnterior.setEnabled(false);
                botonBorrar.setEnabled(false);
            }
            
    }
    
    private void ordenar()
    {
        lista.ordenar();
        mostrarEmpleados();
    }
    
    private void cargarDatosFichero()
    {
        lista.crearFichero();
        JOptionPane.showMessageDialog(this, "Datos cargados en fichero.dat");
    }
    
    private void guardarDatosFichero() throws ClassNotFoundException, IOException 
    {
        ArrayList<Empleado> datosFichero = new ArrayList();
       
        if(lista.existeFichero())
        {
            datosFichero = lista.deserializar();
            borrarLista();
            for(int i = 0; i < datosFichero.size(); i++){
                lista.add(datosFichero.get(i), datosFichero.get(i).getNumero());
            }
            JOptionPane.showMessageDialog(this, "Datos guardados!");
            mostrarEmpleados();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "El fichero no se encuentra o no existe.");
        }
    }
    
    private void diferenciarTipo()
    {
        Empleado e1 = (Empleado) lista.getActualNode().getMain();
        if(e1.getClass().getSimpleName().contains("Analista"))
        {
            labelDato1.setText("Plus Anual:");
            labelDato2.setText("Nombre de Usuario:");
        }
        else
        {
            labelDato1.setText("Extra Mensual:");
            labelDato2.setText("Número de programas:");
        }
    }
    
    private void borrarLista()
    {
        lista = new MyList();
    }
    
    private void avanzar()
    {
        
        lista.avanzar();

        mostrarEmpleados();
        
        if(lista.isFirst())
        {
            botonSiguiente.setEnabled(false);
        }
        botonAnterior.setEnabled(true);
    }
    
    private void retroceder()
    {
       
        lista.retroceder();
        
        mostrarEmpleados();
        
        if(lista.isLast())
        {
            botonAnterior.setEnabled(false);
        }
        botonSiguiente.setEnabled(true);
    }
}
